/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn how to create Gradle builds at https://guides.gradle.org/creating-new-gradle-builds
 */
plugins {
    kotlin("jvm") version "1.3.71"
}

group = "tech.chaosmin"
version = "0.0.1"

repositories {
    maven {
        setUrl("https://maven.aliyun.com/repository/central")
    }
    mavenCentral()
}

dependencies {
    implementation(kotlin("stdlib"))
    implementation(kotlin("reflect"))
    implementation("com.alibaba:fastjson:1.2.68")
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.6.2")
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit:1.3.71")
}